baseURL:
languageCode: en-us
title: Legal Care
taxonomies:
  category: categories
  tag: tags
enableRobotsTXT: true
paginate: 4  # Number of items per page
paginatePath: "page"  # URL path for paginated pages (e.g., /page/2/)
params:
  twitter_user: kris_ray
  twitter_link: https://twitter.com/
  facebook_link: http://www.facebook.com/
  instagram_link: https://www.instagram.com/
  #google_analytics: UA-
  paid_for: Paid for by Language - Kristopher Ray Creative
  form_endpoint: 123456
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
menu:
  main:
    - name: Home
      url: /
      weight: -20
    - name: About
      url: /about/
      weight: -10
    - name: Attorneys
      url: /attorneys/
      weight: -9
    - name: Practice Areas
      url: /practice-areas/
      weight: -8
    - name: Case Studies
      url: /case-studies/
      weight: -7
    - name: Blog
      url: /blog/
      weight: -6
    - name: Contact
      url: /contact/
      weight: -5
    - name: Dropdown
      weight: -4
      hasChildren: true
    - name: Dropdown Item 1
      url: #
      weight: 1
      parent: Dropdown
    - name: Dropdown Item 2
      url: #
      weight: 1
      parent: Dropdown
    - name: Dropdown Item 3
      url: #
      weight: 1
      parent: Dropdown
    